// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgdhsfxglfkcgxtmhjkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZGhzZnhnbGZrY2d4dG1oamtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTM5ODcsImV4cCI6MjA3MzA4OTk4N30._eSkC7t-y8DsJw_2sN6edzvu0A21Uywh0i8X8tbxcf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});